[target.'cfg(target_os = "none")']
runner = "cargo run --package disk-image-builder --"

[alias]
kclippy = "clippy --target x86_64-feebos.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
kbuild = "build --target x86_64-feebos.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-feebos.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
krun = "run --target x86_64-feebos.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --launch-qemu"
ktest = "test --target x86_64-feebos.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --launch-qemu"
